from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
import os

from backend.services.session_tracker import get_full_session


def generate_pdf_report():
    data = get_full_session()

    # 🔥 Ensure reports directory exists
    reports_dir = os.path.join(os.getcwd(), "reports")
    os.makedirs(reports_dir, exist_ok=True)

    file_path = os.path.join(reports_dir, "presage_report.pdf")

    styles = getSampleStyleSheet()
    elements = []

    # 🔴 TITLE
    elements.append(Paragraph("PRESAGE SIEM INCIDENT REPORT", styles["Title"]))
    elements.append(Spacer(1, 12))

    # 🔴 SUMMARY SECTION
    summary = data.get("summary", {})

    elements.append(Paragraph("1. Executive Summary", styles["Heading2"]))

    summary_table = [
        ["Metric", "Value"],
        ["Total Events", summary.get("total_events")],
        ["Pages Visited", summary.get("pages_visited_count")],
        ["Attacks Triggered", summary.get("attacks_triggered")],
        ["Attacks Detected", summary.get("attacks_detected")],
        ["Avg MTTD (sec)", summary.get("average_mttd_seconds")],
        ["Best MTTD", summary.get("best_mttd_seconds")],
        ["Worst MTTD", summary.get("worst_mttd_seconds")],
        ["Improvement Factor", summary.get("improvement_factor")],
    ]

    table = Table(summary_table, colWidths=[220, 120])
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.darkblue),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.whitesmoke),
        ("GRID", (0, 0), (-1, -1), 1, colors.black),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
    ]))

    elements.append(table)
    elements.append(Spacer(1, 20))

    # 🔴 ATTACK ANALYSIS
    elements.append(Paragraph("2. Attack Analysis", styles["Heading2"]))

    for attack, details in data.get("attacks", {}).items():
        elements.append(Paragraph(f"<b>{attack.upper()}</b>", styles["Heading3"]))
        elements.append(Paragraph(f"MTTD: {details.get('mttd_seconds')} seconds", styles["Normal"]))
        elements.append(Paragraph(f"Severity: {details.get('severity')}", styles["Normal"]))
        elements.append(Spacer(1, 10))

    # 🔴 TIMELINE TABLE
    elements.append(Paragraph("3. Event Timeline", styles["Heading2"]))

    timeline_data = [["Time (s)", "Event Type"]]

    for e in data.get("events", [])[:20]:  # limit to first 20 events
        timeline_data.append([
            str(e.get("elapsed_seconds")),
            e.get("event_type")
        ])

    timeline_table = Table(timeline_data, colWidths=[100, 240])
    timeline_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.grey),
        ("GRID", (0, 0), (-1, -1), 1, colors.black),
    ]))

    elements.append(timeline_table)
    elements.append(Spacer(1, 20))

    # 🔴 PLAYBOOK ACTIONS
    elements.append(Paragraph("4. Response Actions (Playbooks)", styles["Heading2"]))

    for attack, details in data.get("attacks", {}).items():
        actions = details.get("playbook_actions", [])
        if actions:
            elements.append(Paragraph(f"{attack}", styles["Heading3"]))
            for a in actions:
                elements.append(Paragraph(f"- {a.get('action')}", styles["Normal"]))
            elements.append(Spacer(1, 10))

    # 🔴 FOOTER
    elements.append(Spacer(1, 20))
    elements.append(Paragraph("Generated by PRESAGE SIEM System", styles["Italic"]))

    # 🔥 BUILD PDF
    doc = SimpleDocTemplate(file_path)
    doc.build(elements)

    return file_path