"""
Presage - LOCAL SIEM ENGINE
Core backend engine for log ingestion, analytics, incidents, and telemetry.
"""

from __future__ import annotations

import datetime
import random
import threading
import time
from collections import defaultdict

from faker import Faker

from backend.modules import brute_force, port_scan, privilege_escalation, windows_failed_logon

fake = Faker()

CONFIG = {
    "workspace_name": "presage-siem-workspace",
    "workspace_id": "presage-local-001",
    "organization": "Presage",
    "client": "Mid-Size Enterprise Client",
    "log_retention_days": 90,
    "alert_threshold": {
        "brute_force_attempts": 5,
        "brute_force_window_seconds": 300,
        "port_scan_ports": 20,
        "port_scan_window_seconds": 60,
        "windows_failed_logon_attempts": 5,
        "windows_failed_logon_window_seconds": 300,
    },
}

LOG_TABLES = {
    "SigninLogs": [],
    "SecurityEvent": [],
    "WindowsEvent": [],
    "AzureActivity": [],
    "NetworkEvents": [],
    "Alerts": [],
    "Incidents": [],
}

_lock = threading.Lock()
incident_counter = {"count": 0}
mttd_records = []

USERNAMES = [
    "admin@presage.io",
    "john.doe@presage.io",
    "sarah.k@presage.io",
    "devops@presage.io",
    "testuser@presage.io",
    "root@presage.io",
]

INTERNAL_IPS = [f"192.168.1.{i}" for i in range(10, 50)]
EXTERNAL_IPS = [
    "45.33.32.156",
    "192.241.235.34",
    "104.18.32.7",
    "103.216.221.12",
    "185.220.101.45",
    "91.108.4.33",
    "198.51.100.23",
    "203.0.113.45",
]


def now_iso():
    return datetime.datetime.now().isoformat()


def generate_signin_log(user=None, success=True, ip=None):
    return {
        "TimeGenerated": now_iso(),
        "UserPrincipalName": user or random.choice(USERNAMES),
        "ResultType": "0" if success else "50126",
        "ResultDescription": "Success" if success else "Invalid username or password",
        "IPAddress": ip or random.choice(INTERNAL_IPS + EXTERNAL_IPS),
        "Location": fake.country() if not success else "India",
        "AppDisplayName": random.choice(["Azure Portal", "Office 365", "VPN Client"]),
        "RiskLevel": "none" if success else random.choice(["low", "medium", "high"]),
        "DeviceDetail": {"operatingSystem": "Windows 10", "browser": "Chrome"},
        "table": "SigninLogs",
    }


def generate_security_event(event_id=4624, user=None):
    event_descriptions = {
        4624: "An account was successfully logged on",
        4625: "An account failed to log on",
        4720: "A user account was created",
        4728: "A member was added to a security-enabled global group",
        4732: "A member was added to a security-enabled local group",
        4756: "A member was added to a security-enabled universal group",
        4672: "Special privileges assigned to new logon",
        4698: "A scheduled task was created",
    }
    return {
        "TimeGenerated": now_iso(),
        "EventID": event_id,
        "Activity": event_descriptions.get(event_id, "Unknown event"),
        "Account": user or random.choice(USERNAMES),
        "Computer": f"PRESAGE-SRV-{random.randint(1,10):02d}",
        "IpAddress": random.choice(INTERNAL_IPS),
        "LogonType": random.choice([2, 3, 7, 10]),
        "SubjectUserName": "SYSTEM",
        "table": "SecurityEvent",
    }


def generate_network_event(src_ip=None, target_ip=None, port=None):
    return {
        "TimeGenerated": now_iso(),
        "SrcIP": src_ip or random.choice(EXTERNAL_IPS),
        "DstIP": target_ip or random.choice(INTERNAL_IPS),
        "DstPort": port or random.randint(1, 65535),
        "Protocol": random.choice(["TCP", "UDP"]),
        "Action": random.choice(["Allow", "Deny"]),
        "BytesSent": random.randint(40, 1500),
        "table": "NetworkEvents",
    }


def generate_azure_activity(user=None, operation=None):
    operations = [
        "Microsoft.Authorization/roleAssignments/write",
        "Microsoft.Compute/virtualMachines/start",
        "Microsoft.KeyVault/vaults/read",
        "Microsoft.Storage/storageAccounts/delete",
        "Microsoft.Authorization/roleAssignments/delete",
    ]
    return {
        "TimeGenerated": now_iso(),
        "Caller": user or random.choice(USERNAMES),
        "OperationName": operation or random.choice(operations),
        "ResourceGroup": "presage-prod-rg",
        "SubscriptionId": "sub-presage-001",
        "ActivityStatus": "Succeeded",
        "ResourceType": "Microsoft.Authorization",
        "table": "AzureActivity",
    }


def generate_windows_event(
    channel="Application",
    event_id=1000,
    provider="Custom-SIEM-Simulator",
    level="Information",
    message="Synthetic Windows event generated by the SIEM simulator",
    target_user=None,
    source_ip=None,
):
    return {
        "TimeGenerated": now_iso(),
        "Channel": channel,
        "EventID": event_id,
        "RecordId": random.randint(100000, 999999),
        "Provider": provider,
        "Level": level,
        "Computer": f"PRESAGE-WS-{random.randint(1,5):02d}",
        "Message": message,
        "Keywords": "",
        "TargetUserName": target_user,
        "SourceIp": source_ip,
        "table": "WindowsEvent",
    }


class DetectionEngine:
    def __init__(self, alert_callback):
        self.alert_callback = alert_callback
        self._failed_logins = defaultdict(list)
        self._port_scans = defaultdict(list)
        self._bruteforce_cooldown = {}
        self._windows_failed_logons = defaultdict(list)
        self._windows_failed_logon_cooldown = {}

    def rule_brute_force(self, log):
        brute_force.analyze(self, log, CONFIG, _lock)

    def rule_privilege_escalation(self, log):
        privilege_escalation.analyze(self, log, CONFIG, _lock)

    def rule_port_scan(self, log):
        port_scan.analyze(self, log, CONFIG, _lock)

    def rule_windows_failed_logon(self, log):
        windows_failed_logon.analyze(self, log, CONFIG, _lock)

    def analyze(self, log):
        self.rule_brute_force(log)
        self.rule_privilege_escalation(log)
        self.rule_port_scan(log)
        self.rule_windows_failed_logon(log)


class AlertManager:
    def __init__(self):
        self.attack_start_times = {}

    def mark_attack_start(self, attack_type):
        self.attack_start_times[attack_type] = time.time()
        print(f"\n  [ATTACK STARTED] {attack_type} - timer started")

    def create_incident(self, alert):
        with _lock:
            incident_counter["count"] += 1
            inc_id = incident_counter["count"]

        alert_time = time.time()
        rule_name = alert["rule"]
        attack_map = {
            "Brute Force Login Attack Detected": "brute_force",
            "Privilege Escalation - Admin Role Assigned": "privilege_escalation",
            "Port Scan / Network Reconnaissance Detected": "port_scan",
            "Windows Failed Logon Burst Detected": "windows_failed_logon",
        }
        attack_key = attack_map.get(rule_name)
        mttd_seconds = None
        if attack_key and attack_key in self.attack_start_times:
            mttd_seconds = round(alert_time - self.attack_start_times[attack_key], 2)
            mttd_records.append({
                "attack": rule_name,
                "mttd_seconds": mttd_seconds,
                "timestamp": now_iso(),
            })

        incident = {
            "IncidentNumber": inc_id,
            "Title": alert["rule"],
            "Severity": alert["severity"],
            "Status": "New",
            "CreatedTime": now_iso(),
            "MITRETactic": alert["mitre"],
            "AffectedEntity": alert.get("entity_user") or alert.get("entity_ip"),
            "Evidence": alert["evidence"],
            "SourceTable": alert["table"],
            "RecommendedAction": alert["recommended_action"],
            "MTTD_seconds": mttd_seconds,
            "PlaybookTriggered": alert["severity"] == "High",
        }

        with _lock:
            LOG_TABLES["Alerts"].append(alert)
            LOG_TABLES["Incidents"].append(incident)

        return incident, mttd_seconds


def ingest_log(log):
    table = log.get("table", "SecurityEvent")
    with _lock:
        if table not in LOG_TABLES:
            LOG_TABLES[table] = []
        LOG_TABLES[table].append(log)
        if len(LOG_TABLES[table]) > 500:
            LOG_TABLES[table] = LOG_TABLES[table][-500:]


def get_logs(table, limit=50):
    with _lock:
        return list(reversed(LOG_TABLES.get(table, [])[-limit:]))


def get_incidents():
    with _lock:
        return list(reversed(LOG_TABLES["Incidents"]))


def get_alerts():
    with _lock:
        return list(reversed(LOG_TABLES["Alerts"]))


def get_mttd_summary():
    with _lock:
        if not mttd_records:
            return {"average": 0, "records": []}
        avg = round(sum(r["mttd_seconds"] for r in mttd_records) / len(mttd_records), 2)
        return {"average": avg, "records": list(mttd_records)}


def get_stats():
    with _lock:
        return {
            "total_logs": sum(len(v) for k, v in LOG_TABLES.items() if k not in ["Alerts", "Incidents"]),
            "total_alerts": len(LOG_TABLES["Alerts"]),
            "total_incidents": len(LOG_TABLES["Incidents"]),
            "high_severity": sum(1 for i in LOG_TABLES["Incidents"] if i["Severity"] == "High"),
            "sources_active": len([k for k in LOG_TABLES.keys() if k not in ["Alerts", "Incidents"]]),
        }


